version: '3'
services:

  database:
    container_name: database
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wallet
    ports:
      - "54320:5432"

  wallet:
    container_name: crypto_wallet
    build: .
    ports:
      - "8189:8189"
    restart: always
    links:
      - database
